### PR TITLE
Build with ASDF 3.3

### PR DESCRIPTION
**Pull request by fare**
Stop using deprecated system-directory-pathname.

Modernize the .asd file.

### CODE REVIEW

**Comment by fare** [comment]
Ping.

I had forgotten to update the travis file for renamed test system. Fixed.

**Comment by fare** [comment]
The above checks succeeded for all implementations but clisp. Looks like a clisp bug.

**Comment by DalekBaldwin** [comment]
The failure has something to do with the old stefil's use of metabang-bind. That test library is deprecated anyway so I tried with the more recent hu.dwim.stefil, but it's blowing up ECL in even weirder ways. It's important that a language extension tool like this is fully cross-compatible, so I'll merge this if I can find another test library that plays nice.

**Comment by DalekBaldwin** [comment]
You commented out `:long-description`; is that out of fashion now, or is there a better way to populate it from a static file?

**Comment by DalekBaldwin** [comment]
Followup from personal conversation: it is indeed a bit silly to force all consumers of a lightweight generic metaprogramming library to load a big `README.md`-sized string into their Lisp image, so I'm just removing `:long-description` from the system spec for now. Merged changes from this PR into `dev`.

**Pull request closed without merging**
